spring:
  application:
    name: 'ali-bouali-security'
  datasource:
    url: 'jdbc:h2:file:securitydb'
    username: sa
    password: password
    initialization-mode: always
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true